version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./public/:/var/www/html/public/
            - ./mvc/:/var/www/html/mvc/
            - ./index.css:/var/www/html/index.css
            - ./index.php:/var/www/html/index.php
        ports:
            - 8000:80 
    db:
        container_name: db
        image: mysql:5.7
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_DATABASE: dkhp
            MYSQL_USER: admin
            MYSQL_PASSWORD: mysql12345
        ports:
            - "3306:3306"
        volumes: # khởi tạo dữ liệu
            - ./db/dkhp_fix.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./mysql/my.cnf:/etc/my.cnf
        # command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: mysql12345